modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="cataclysmic_realms"
version="1.0.0"
displayName="Cataclysmic Realms"
credits="The_WereF0X"
displayURL="https://discord.gg/3CMa2f5jzS"
updateJSONURL="https://discord.gg/3CMa2f5jzS"
authors="The_WereF0X"

[[dependencies.cataclysmic_realms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




